name: CI5

on:
  workflow_dispatch:
    inputs:
      benchmark-result:
        required: true
        type: string
        default: |
          [
            {
                "name": "My Custom Smaller Is Better Benchmark - CPU Load",
                "unit": "Percent",
                "value": 50
            },
            {
                "name": "My Custom Smaller Is Better Benchmark - Memory Used",
                "unit": "Megabytes",
                "value": 100,
                "range": "3",
                "extra": "Value for Tooltip: 25\nOptional Num #2: 100\nAnything Else!"
            }
          ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BENCHMARK_JSON: ${{ inputs.benchmark-result }}

    steps:
      - name: Generate benchmark result
        # run: |
        #   echo -e "${{ inputs.benchmark-result }}" > output.json
        #   realpath output.json
        run: |
          echo "$BENCHMARK_JSON" > output.json
          echo "--- Verifying content of output.json ---"
          cat output.json
          echo "----------------------------------------"

      - name: Generate a token to access cyril0124/test-ci-benchmark
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.REPO_ACCESS_APP_ID }}
          private-key: ${{ secrets.REPO_ACCESS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: test-ci-benchmark
          
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: My test benchmark results
          tool: "customSmallerIsBetter"
          output-file-path: output.json
          gh-repository: 'github.com/cyril0124/test-ci-benchmark'
          gh-pages-branch: gh-pages
          auto-push: true
          github-token: ${{ steps.generate_token.outputs.token }}



