name: CI5

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate a token to access cyril0124/test-ci-benchmark
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.REPO_ACCESS_APP_ID }}
          private-key: ${{ secrets.REPO_ACCESS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: test-ci-benchmark
          
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: My test benchmark results
          tool: "customSmallerIsBetter"
          output-file-path: output.json
          gh-repository: 'github.com/cyril0124/test-ci-benchmark'
          gh-pages-branch: gh-pages
          auto-push: true
          github-token: ${{ steps.generate_token.outputs.token }}



